# Generated by Django 4.2.2 on 2023-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0002_alter_reporte_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="puntaje_riesgo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
