# Generated by Django 4.2.7 on 2023-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_resultado_puntaje_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='reporte',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
