# Generated by Django 4.2.7 on 2023-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_usuario_remove_reporte_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=45)),
                ('lights', models.CharField(max_length=45)),
            ],
        ),
    ]
