# Generated by Django 4.2.7 on 2023-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
