# Generated by Django 4.2.7 on 2023-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_camera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='video',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
