# Generated by Django 4.2.7 on 2023-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_camera_video_alter_camera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='number',
            field=models.CharField(default=True, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.BooleanField(verbose_name='Is Active'),
        ),
    ]
