# Generated by Django 4.2.7 on 2023-11-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_alter_camera_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefonoEmergencia',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='number',
            field=models.IntegerField(),
        ),
    ]
