# Generated by Django 4.2.7 on 2023-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_usuario_telefonoemergencia_alter_camera_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identifier',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
