# Generated by Django 4.2.7 on 2023-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_light_remove_camera_lights'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
