# Generated by Django 4.2.7 on 2023-11-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_light_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='status',
            field=models.BooleanField(verbose_name='Is on'),
        ),
    ]
